# Generated by Django 5.2.1 on 2026-04-20 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='LoreForge', max_length=100)),
                ('hero_title', models.CharField(default='Your TTRPG world, organised.', max_length=200)),
                ('hero_subtitle', models.CharField(blank=True, max_length=400)),
                ('hero_body', models.TextField(blank=True)),
                ('cta_text', models.CharField(default='Get started', max_length=100)),
                ('cta_url', models.CharField(default='/accounts/register/', max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Configuration',
                'verbose_name_plural': 'Site Configuration',
            },
        ),
    ]
